apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- aerospike-kubernetes-operator.clusterserviceversion.yaml

commonAnnotations:
  containerImage: controller:latest
  createdAt: 2023-06-01T09:25:18UTC
